Application:
    Name: Wireless Config
    Description: WiFi setup
    Icon: pictures/ST4439_ST_logo.png
    Type: script
    Board:
        List: all
    Script:
        Start: echo "Wireless Config - Managing TCP connections and network settings"
    Action:
        button_release_event: script_management
        button_press_event: highlight_eventBox
